// <auto-generated />
using System;
using Jobbook.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Jobbook.Migrations
{
    [DbContext(typeof(JobbookContext))]
    [Migration("20181127153449_InitialVacature")]
    partial class InitialVacature
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Jobbook.Models.JobbookVacatureModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("JobCompanyID");

                    b.Property<string>("JobContactEmail");

                    b.Property<int>("JobContactTel");

                    b.Property<int>("JobContractHours");

                    b.Property<string>("JobContractType");

                    b.Property<int>("JobDaysOff");

                    b.Property<string>("JobDescription");

                    b.Property<bool>("JobExpired");

                    b.Property<DateTime>("JobExpiredDate");

                    b.Property<string>("JobLocation");

                    b.Property<DateTime>("JobPublished");

                    b.Property<int>("JobSalary");

                    b.Property<string>("JobSeniority");

                    b.Property<string>("JobTitle");

                    b.HasKey("ID");

                    b.ToTable("JobbookVacatureModel");
                });
#pragma warning restore 612, 618
        }
    }
}
